data:
  image: busybox
  command: cat
  volumes:
    - /data

mongo:
  image: mongo:2.4
  command: mongod --setParameter textSearchEnabled=true

backend:
  image: berekuk/questhub_backend
  links:
    - mongo
  volumes_from:
    - data
  env_file: config/prod

app1:
  image: berekuk/questhub_app
  links:
    - mongo
  volumes_from:
    - data
  env_file: config/prod

app2:
  image: berekuk/questhub_app
  links:
    - mongo
  volumes_from:
    - data
  env_file: config/prod

www:
  image: berekuk/questhub_www
  env_file: config/prod

frontend:
  image: berekuk/questhub_frontend
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /home/ubuntu/ssl:/config/ssl
  volumes_from:
    - data
    - www
  links:
    - app1
    - app2
  env_file: config/prod
