data:
  image: busybox
  command: cat
  volumes:
    - /data

mongo:
  image: mongo:2.4
  volumes_from:
    - data # for pull-db.pl
  command: mongod --setParameter textSearchEnabled=true --smallfiles

backend:
  build: ./backend
  links:
    - mongo
  volumes:
    - backend:/play/backend
  volumes_from:
    - data
  env_file: config/dev

app:
  build: ./app
  links:
    - mongo
  volumes:
    - backend:/play/backend
    - app:/play/app
  volumes_from:
    - data
  env_file: config/dev

www:
  build: ./www
  volumes:
    - www:/www
  ports:
    - "8000:80"
    - "9090:9090"
  links:
    - app
  env_file: config/dev

# code editor
dev:
  build: ./dev
  links:
    - mongo
  volumes_from:
    - www
    - app
  environment:
    TERM: xterm-256color
